import type { Metadata } from 'next';
import { Barlow_Condensed, Inter } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });
const barlow = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['300', '500', '700', '800', '900'],
  
});

export const metadata: Metadata = {
  title: 'Kim Trung',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        'bg-white text-slate-900 antialiased light',
        barlow.className
      )}
    >
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </head>
      <body className="min-h-screen bg-slate-50 antialiased flex flex-col">
         <header className='w-full'>
            <div className="container mx-auto flex items-center justify-between">
              <Navbar />
            </div>
         </header>
          <main className="flex w-full flex-1 flex-col overflow-hidden">
            {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}
